### ISSUE TITLE
Enable forwarding of query parameters

### ISSUE THREAD

**Issue by barnettx** [opengovsg/GoGovSG#1260]
Related to #17 

Turns out the bulk URLs that customers want to create using an API are actually variations of the same URL but with different query parameters. Safely enabling the forwarding of query parameters will mean fewer shortlinks created.

**TODO**:
- [ ] Check that longURL has the same origin as user before forwarding query params (as a security measure)
- [ ] Add UI for user to enable query params
- [ ] Add flag to URL model to forward query params

**Comment by liangyuanruo** [comment]
> Check that longURL has the same origin as user before forwarding query params

I assume this means that `user@abc.gov.sg` can only enable query parameter forwarding for website domains at `abc.gov.sg`? This can cause performance problems if the user has to be retrieved from the database each time a short link is visited - to get around this, the user object will also have to be cached in Redis.

@yong-jie @LoneRifle FYI

**Comment by LoneRifle** [comment]
Not necessarily - on a cold hit, compare the user and link domains. if they don't match, log so, and handle the response in a manner that informs the user/creator that something is wrong, putting something appropriate in Redis.

The alternative is to simply validate the data on creation/update, which might be easier to reason about, but might introduce problems if updates are done out-of-band.

**Comment by liangyuanruo** [comment]
Your alternative is good, if we have the necessary UX changes

**Comment by yong-jie** [comment]
i would prefer the alternative too, something like our isFile flag to track if forwarding is enabled? 

edge case: a link that forwards params getting transferred to user with different domain should have param forwarding disabled(?)

**Comment by liangyuanruo** [comment]
Or if the admin changes the long URL itself from one that supports query params forwarding to one that does not.

**Comment by LoneRifle** [comment]
Closing in favour of #17
