### ISSUE TITLE
Epic for GoGov Health setup

### ISSUE THREAD

**Issue by gweiying** [opengovsg/GoGovSG#1801]
This issue tracks the progress of the setup for For.sg (Go.gov.sg for health).

The tasks are broken down into:

- Infrastructure setup
- Code changes
- Miscellaneous fixes
- Post-setup

## Infrastructure setup 
See Google Docs for [detailed instructions on infrastructure setup](https://docs.google.com/document/d/1Rfv2Wo-8ECI3Z6rQmTfmLMGOdpAHPmy4z2DNNtEXAyA/edit#heading=h.skwcbv632jd0)

### Staging

  - [x] Networking (VPC, Subnets, Security Groups, Route Tables, IG, NATG)
  - [x] RDS
  - [x] Redis
  - [x] EB
  - [x] S3
  - [x] ACM
  - [x] Lambda 
  - [x] SES
  - [x] Batch Job
  - [x] Cloudflare - set up https://staging.for.sg to point to EB
### Production
  - [x] Networking (VPC, Subnets, Security Groups, Route Tables, IG, NATG)
    - [x] Add rules for inbound Cloudflare IP addresses (after deployment)
  - [x] RDS
  - [x] Redis
  - [x] EB 
  - [x] S3
  - [x] ACM
  - [x] Lambda
  - [x] SES
  - [x] Batch Job (setup when deployment is done)
    - [x] Setup is done
    - [x] Left with configuring EventBridge to start Batch backups
  - [x] Cloudflare - set up https://for.sg domain to point to EB  (setup when deployment is done)
## Code changes
  - [x] Add CI/CD to deploy applications https://github.com/opengovsg/GoGovSG/pull/1799
  - [x] Production - Update CI/CD variables to deploy to production environment when assets are ready
    - [x] Verify that Lambda is setup
    - [x] Verify that EB is setup
    - [x] Verify that RDS is setup
  - [x] Assets #1812
    - [x] Create assets and locales for `/health`
    - [x] Fix ternary operators to allow for different assets - `assetVariant` currently allows only switching between `'gov'` and `'edu'` variants 
#### Database migration issue 
  - [x] Code changes https://github.com/opengovsg/GoGovSG/pull/1800
  - [x] Run migrations to fix issue on `health-staging`
  - [x] Run migrations to fix issue on `edu-staging`
  - [x] Run migrations to fix issue on `edu-prod`
  - [x] Run migrations to fix issue on `gogov-staging`
  - [x] Run migrations to fix issue on `gogov-prod`
  - [x] Release code changes to production

## Post-setup (to be fleshed out)
 - [x] Setup alarms and logging to #gogovalerts
   - [x] EB alarms
   - [x] HTTP alarms
   - [x]  DB alarms
 - [x] Setup Cronitor for Batch Job
 - [x] Setup Pingdom
 - [ ] Anything else??

**Comment by gweiying** [comment]
Done and closing!
