### ISSUE TITLE
Epic for GoGov infra updates and monitoring (WIP)

### ISSUE THREAD

**Issue by gweiying** [opengovsg/GoGovSG#1811]
### Essential upgrades
- [ ] Upgrade functions from Node 12 -> Node 14 across all three environments
- [x] EB: Upgrade EB machines from Amazon Linux 1 -> Amazon Linux 2 for `gosg-stag` and `gosg-prod`  #1839 
Documentation [here](https://docs.google.com/document/d/1wpMcp1qY9-gR5XY5NvpparZYTLEtJgasNENCUe9K7Kk/edit#heading=h.3zs5qeqjfr3x)

### Cleanups
- [x] Clean up UAT environment

### Nice to haves
- [ ] Set up Datadog monitoring
