### ISSUE TITLE
Tracking error metrics

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/GoGovSG#700]
Implement the following tracking code for custom events using _gtag_, for both success and error cases:

## Log in
Component
- [x] Sign In
- [x] Submit OTP (related to SGmail delay)

## User Page
Component
- [x] Create link > url
- [x] Create link > from file
- [x] Download Links button

## Link Drawer
- [x] Transfer ownership
- [x] QR Code generation (SVG or PNG)

## Analytics
- [x] Fetching of analytics data

**Comment by lisatjide** [comment]
Pivoting this to log errors on Sentry instead

**Comment by lisatjide** [comment]
Updating the title since the team has decided to log all errors on GA. FYI @Oxiang
